name: Security Monitor GitHub Action

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - "dependabot/**"
concurrency:
  group: security-monitor
  cancel-in-progress: true

jobs:
  security_monitor:
#     if: ${{ github.head_ref === "dependabot/check" }}
    runs-on: ubuntu-latest
    name: Security Monitor
    steps:
    - name: Security Monitor
      uses: alesiaviktorchyk/security-check-action@master
      with:
        gh-pat: ${{ secrets.gh_pat }} # github personal access token
        action-user: ${{ secrets.action_user }}
