name: Security Monitor GitHub Action

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - "*"

jobs:
  security_monitor:
    if: contains(github.head_ref, '!dependabot')
    runs-on: ubuntu-latest
    name: Security Monitor
    concurrency: security-monitor
    steps:
    - name: Security Monitor
      uses: alesiaviktorchyk/security-check-action@master
      with:
        gh-pat: ${{secrets.gh_pat}} # github personal access token
        action-user: ${{ secrets.action_user }}
