name: Security Monitor GitHub Action

on:
  pull_request_target:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - "*"

jobs:
  security_monitor:
    if: contains(github.head_ref, 'dependabot')
    runs-on: ubuntu-latest
    name: Security Monitor
    concurrency: security-monitor
    steps:
    - name: Security Monitor
      uses: alesiaviktorchyk/security-check-action@master
      with:
        gh-pat: ${{secrets.gh_pat}} # github personal access token
        action-user: ${{ secrets.action_user }}

  pass_status:
    if: contains(github.head_ref, 'dependabot')
    runs-on: ubuntu-latest
    name: Pass Status for dependabot
    permissions: 
      statuses: write
    concurrency: pass-dependabot-status-check
    steps:
      - name: pass status
        run: |
          curl \
            -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: Bearer ${{secrets.gh_pat}}" \
            https://api.github.com/repos/${{github.repository}}/statuses/${{github.sha}} \
            -d '{"state":"success", "context": "security-monitor"}'
