name: Security Monitor GitHub Action

on:
  push:
#     types:
#       - opened
#       - reopened
#       - synchronize
#       - review_requested
    branches-ignore:
      - "dependabot/**"
concurrency:
  group: security-monitor
  cancel-in-progress: true

jobs:
  security_monitor:
    runs-on: ubuntu-latest
    name: Security Monitor
    steps:
    - name: Security Monitor
      uses: alesiaviktorchyk/security-check-action@master
      with:
        gh-pat: ${{ secrets.gh_pat }} # github personal access token
        action-user: ${{ secrets.action_user }}
