name: Pass status check for dependabot

# read-write repo token
# access to secrets
on:
  workflow_run:
    workflows: ["Security Monitor GitHub Action"]
    types:
      - completed

jobs:
  pass_status:
    runs-on: ubuntu-latest
    name: Pass Status for dependabot
    concurrency: pass-dependabot-status-check
    permissions: 
      statuses: write
    if: >
      ${{ github.event.workflow_run.event == 'pull_request' &&
      contains(github.head_ref, 'dependabot') }}
    steps:
      # - name: pass status
      #   run: |
      #     curl \
      #       -X POST \
      #       -H "Accept: application/vnd.github.v3+json" \
      #       -H "Authorization: Bearer ${{secrets.GITHUB_TOKEN}}" \
      #       https://api.github.com/repos/${{github.repository}}/statuses/${{github.sha}} \
      #       -d '{"state":"success", "context": "security-monitor"}'
      - name: pass status
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.repos.createCommitStatus({
              context: 'security-monitor',
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: context.sha,
              state: 'success'
            });
